=== trigger-happy/Cerberus/resources/stage.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://cerberus.compsat.org" targetNamespace="http://cerberus.compsat.org" elementFormDefault="qualified">
	<xs:attributeGroup name="question_attributes">
		<xs:attribute name="time_limit" type="xs:positiveInteger"/>
		<xs:attribute name="score" type="xs:positiveInteger" default="1" />
		<xs:attribute name="id" type="xs:ID"/>
	</xs:attributeGroup>
	<xs:element name="stage">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="welcome_msg" type="xs:string" minOccurs="0"/>
				<xs:choice maxOccurs="unbounded">
					<xs:element name="identification">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="q" type="xs:string"/>
								<xs:element name="a" type="xs:string"/>
							</xs:sequence>
							<xs:attributeGroup ref="question_attributes"/>
						</xs:complexType>
					</xs:element>
					<xs:element name="choose">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="q" type="xs:string"/>
								<xs:element name="choice" maxOccurs="unbounded">
									<xs:complexType>
										<xs:simpleContent>
											<xs:extension base="xs:string">
												<xs:attribute name="answer" type="xs:boolean" default="false"/>
											</xs:extension>
										</xs:simpleContent>
									</xs:complexType>
								</xs:element>
							</xs:sequence>
							<xs:attributeGroup ref="question_attributes"/>
							<xs:attribute name="multiple" type="xs:boolean" default="false"/>
						</xs:complexType>
					</xs:element>
				</xs:choice>
			</xs:sequence>
			<xs:attribute name="time_limit" type="xs:integer"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== trigger-happy/Cerberus/resources/lulwut1.xml
<?xml version="1.0"?>
<stage xmlns="http://cerberus.compsat.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://cerberus.compsat.org stage.xsd" time_limit="60">
    <welcome_msg>ADURDURDUR</welcome_msg>
    <choose score="1" id="1">
        <q>Where am I?</q>
        <choice answer="true">Here</choice>
        <choice>There</choice>
        <choice>No where</choice>
        <choice>everywhere</choice>
    </choose>
    <choose score="1" id="2">
        <q>How many licks does it take to get to the center of a tootsie roll?</q>
        <choice>5</choice>
        <choice>6</choice>
        <choice>10</choice>
        <choice answer="true">500000</choice>
    </choose>
    <choose score="1" id="3">
        <q>Where am I?</q>
        <choice answer="true">Here</choice>
        <choice>There</choice>
        <choice>No where</choice>
        <choice>everywhere</choice>
    </choose>
    <choose score="1" id="4">
        <q>How many licks does it take to get to the center of a tootsie roll?</q>
        <choice>100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000022032032032020320302032032032030203203012030124591458745903426928367587516543965409706578537863567869086978756564758965078763126487769085436258960875398</choice>
        <choice>6</choice>
        <choice>10</choice>
        <choice answer="true">500000</choice>
    </choose>
</stage>

=== trigger-happy/Cerberus/resources/b3.xml
<?xml version="1.0"?>
<stage xmlns="http://cerberus.compsat.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://cerberus.compsat.org stage.xsd">
    <welcome_msg>Young people now-a-days are a sucker for punishment</welcome_msg>
    <identification score="9" time_limit="1" id="1">
        <q>WHAT IS FEDORA MAN'S FULL NAME(with titles)</q>
        <a>James Andrew Chung Choa ROTC phD md esquire bachelor of science in computer science double major minor super saiyan magical slave leader butler girl no maid guy</a>
    </identification>
    <identification score="9" time_limit="1" id="2">
        <q>What does dota stands for?</q>
        <a>Defense of the ancients</a>
    </identification>
</stage>

=== trigger-happy/Cerberus/resources/stage2.xml
<?xml version="1.0"?>
<stage xmlns="http://cerberus.compsat.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://cerberus.compsat.org stage.xsd" time_limit="45">
    <welcome_msg>ROUND 2! Select all possible answers</welcome_msg>
    <choose multiple="true" score="3" id="1">
        <q>Who among the following does not belong to Gai's team?</q>
        <choice>Neji</choice>
        <choice answer="true">Chouji</choice>
        <choice answer="true">Hinata</choice>
        <choice>Tenten</choice>
    </choose>
    <choose multiple="true" score="3" id="2">
        <q>What are the names of Gaara's siblings?</q>
        <choice>Tenten</choice>
        <choice answer="true">Temari</choice>
        <choice>Ken Lee</choice>
        <choice answer="true">Kankurou</choice>
    </choose>
    <choose multiple="true" score="1" id="3">
        <q>Who among the following possess a Bloodline Limit ability?</q>
        <choice>Uzumaki Naruto</choice>
        <choice answer="true">Uchiha Sasuke</choice>
        <choice>Haruno Sakura</choice>
        <choice answer="true">Hyuuga Neji</choice>
    </choose>
    <choose multiple="true" score="1" id="4">
        <q>Who among the following are part of the Shichibukai?</q>
        <choice answer="true">Flamingo</choice>
        <choice answer="true">Blackbeard</choice>
        <choice>Dragoon</choice>
        <choice>Whitebeard</choice>
    </choose>
</stage>

=== trigger-happy/Cerberus/resources/c1.xml
<?xml version="1.0"?>
<stage xmlns="http://cerberus.compsat.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://cerberus.compsat.org stage.xsd">
    <welcome_msg></welcome_msg>
    <choose score="1" id="1">
        <q>f</q>
        <choice answer="true"></choice>
        <choice></choice>
        <choice></choice>
        <choice></choice>
    </choose>
    <choose score="1" id="2">
        <q>new question</q>
        <choice answer="true"></choice>
        <choice></choice>
        <choice></choice>
        <choice></choice>
    </choose>
</stage>

=== trigger-happy/Cerberus/resources/lulwut2.xml
<?xml version="1.0"?>
<stage xmlns="http://cerberus.compsat.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://cerberus.compsat.org stage.xsd" time_limit="5">
    <welcome_msg>You guys are screwed</welcome_msg>
    <choose multiple="true" score="10" id="1">
        <q>What is a man?</q>
        <choice answer="true">A miserable pile of bullshit</choice>
        <choice>huh?</choice>
        <choice>FEDORA MAN</choice>
        <choice answer="true">a sentient being</choice>
    </choose>
    <choose multiple="true" score="8" id="2">
        <q>Why am i the only one testing?</q>
        <choice>because no one wants to</choice>
        <choice answer="true">not enough laptop</choice>
        <choice>it's my birthday</choice>
        <choice answer="true">they want to</choice>
    </choose>
    <choose multiple="true" score="10" id="3">
        <q>What is a man?</q>
        <choice answer="true">A miserable pile of bullshit</choice>
        <choice>huh?</choice>
        <choice>FEDORA MAN</choice>
        <choice answer="true">a sentient being</choice>
    </choose>
    <choose multiple="true" score="8" id="4">
        <q>Why am i the only one testing?</q>
        <choice>because no one wants to</choice>
        <choice answer="true">not enough laptop</choice>
        <choice>it's my birthday</choice>
        <choice answer="true">they want to</choice>
    </choose>
</stage>

=== trigger-happy/Cerberus/resources/stage3.xml
<?xml version="1.0"?>
<stage xmlns="http://cerberus.compsat.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://cerberus.compsat.org stage.xsd">
    <welcome_msg>Young people now-a-days are a sucker for punishment</welcome_msg>
    <identification score="9" time_limit="30" id="1">
        <q>WHAT IS FEDORA MAN'S FULL NAME(with titles)</q>
        <a>James Andrew Chung Choa ROTC phD md esquire bachelor of science in computer science double major minor super saiyan magical slave leader butler girl no maid guy</a>
    </identification>
    <identification score="9" time_limit="30" id="2">
        <q>What does dota stands for?</q>
        <a>Defense of the ancients</a>
    </identification>
    <identification score="9" time_limit="30" id="3">
        <q>WHAT IS FEDORA MAN'S FULL NAME(with titles)</q>
        <a>James Andrew Chung Choa ROTC phD md esquire bachelor of science in computer science double major minor super saiyan magical slave leader butler girl no maid guy</a>
    </identification>
    <identification score="9" time_limit="1" id="4">
        <q>What does dota stands for?</q>
        <a>Defense of the ancients</a>
    </identification>
    <choose multiple="true" score="5" time_limit="30" id="5">
        <q>Which ninjas among the following do not belong to the village of Konoha?</q>
        <choice>Tenten</choice>
        <choice answer="true">Temari</choice>
        <choice answer="true">Kin</choice>
        <choice>Rock lee</choice>
    </choose>
    <identification score="10" time_limit="30" id="6">
        <q>What is the name of Naruto's teacher who is known to be the frog hermit?</q>
        <a>Jiraiya</a>
    </identification>
</stage>

=== trigger-happy/Cerberus/resources/b1.xml
<?xml version="1.0"?>
<stage xmlns="http://cerberus.compsat.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://cerberus.compsat.org stage.xsd" time_limit="60">
    <welcome_msg>ADURDURDUR</welcome_msg>
    <choose score="1" id="1">
        <q>new question</q>
        <choice answer="true"></choice>
        <choice></choice>
        <choice></choice>
        <choice></choice>
    </choose>
    <choose score="1" id="2">
        <q>How many licks does it take to get to the center of a tootsie roll?</q>
        <choice>5</choice>
        <choice>6</choice>
        <choice>10</choice>
        <choice answer="true">500000</choice>
    </choose>
    <choose score="1" id="3">
        <q>f</q>
        <choice answer="true"></choice>
        <choice></choice>
        <choice></choice>
        <choice></choice>
    </choose>
</stage>

=== trigger-happy/Cerberus/resources/lulwut4.xml
<?xml version="1.0"?>
<stage xmlns="http://cerberus.compsat.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://cerberus.compsat.org stage.xsd">
    <welcome_msg>MORTAL KOMBAT</welcome_msg>
    <identification score="1" time_limit="1" id="1">
        <q>What is 1+1</q>
        <a>2</a>
    </identification>
    <identification score="1" time_limit="1" id="2">
        <q>I have 4 cakes. However, you do not see the cakes.  Therefore, in your reality I have no cake. But, the fact that I have a cake is still true.  How do you solve this problem?</q>
        <a>THE CAKE IS A LIE</a>
        <a>THE CAKE IS ALSO DELICIOUS</a>
    </identification>
</stage>
